### PR TITLE
fix(dependencies): Update dependencies and related code changes

### LINKED ISSUE #241: Update dependencies
Update dependencies for security reasons

### PR DESCRIPTION
**Pull request by Retro64**
close #241

### CODE REVIEW

File: test/unit/index.ts [hunk 1]
```diff
@@ -24,45 +25,51 @@ describe('oauth tooling', () => {
...
     it('if refreshToken is not defined (in case of Refresh Token Grant)', () => {
-      expect(getAccessToken.bind(undefined, {
-        ...config,
-        grantType: OAuthGrantType.REFRESH_TOKEN_GRANT
-      })).to.throw(TypeError);
+      const brokenConfig = {...config, grantType: OAuthGrantType.REFRESH_TOKEN_GRANT} as unknown as OAuthConfig;
+
+      expect(getAccessToken.bind(undefined,
+        brokenConfig
+        )).to.throw(TypeError);
```
Comment (bzums) [inline test/unit/index.ts]: indent

**Comment by bzums** [comment]
👍

**Comment by Retro64** [comment]
:+1:
