### PR TITLE
fix(express-tooling): pass logger to getTokenInfo and log error

### LINKED ISSUE #211: `authenticationMiddleware` should pass logger to `getTokenInfo` call
Currently `authenticationMiddleware` is not passing down the logger:

https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L202

Furthermore if there is an error it is not logged in https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L207

### PR DESCRIPTION
**Pull request by shuhei**
close #211 

Also bumping version to 2.0.6 (patch).

### CODE REVIEW

File: src/express-tooling.ts [hunk 1]
```diff
@@ -199,12 +199,15 @@ const authenticationMiddleware: authenticationMiddleware = (options) => {
...
     } else {
-      getTokenInfo(tokenInfoEndpoint, accessToken)
+      getTokenInfo(tokenInfoEndpoint, accessToken, logger)
         .then(setTokeninfo(req))
         .then(next)
         // TODO we should send 500 for issues with network etc.
         //      we should send HttpStatus.UNAUTHORIZED for invalid token
-        .catch(err => notAuthenticatedHandler(res, logOrNothing, HttpStatus.UNAUTHORIZED));
+        .catch(err => {
+          logOrNothing.warn(`Error while getting token info: ${err}`);
```
Comment (bzums) [inline src/express-tooling.ts]: If `err` is an object this will yield `"[object Object]"`.

I would suggest:

```ts
logOrNothing.warn(`Error while getting token info`, err);
```

...because the logger accepts an error object as second parameter which is stringified reasonably.

Comment (shuhei) [reply src/express-tooling.ts]: Ah, makes sense. Now I noticed the logger's second argument was `any`. Pushed another commit to fix this and another line that was using a template literal.

**Comment by Retro64** [comment]
:+1:

**Comment by bzums** [comment]
👍
