### PR TITLE
123 mock failing server

### LINKED ISSUE #123: Mock Tooling: add mock util to test failing token request
Something like `mockBrokenAccessTokenEndpoint` (name TBD), 
  which responds with `status >= 400`

### PR DESCRIPTION
**Pull request by Retro64**
close #123

### CODE REVIEW

File: src/mock-tooling/index.ts [hunk 1]
```diff
@@ -20,36 +20,68 @@ function generateToken(): Token {
...
 
     return [HttpStatus.OK, newToken];
   });
 }
 
+export function mockAccessTokenEndpointWithErrorResponse(options: MockOptions, httpStatus: number, responseBody?: object): void {
+  mockEndpointWithErrorResponse(options, httpStatus, responseBody);
+}
+
+export function mockTokeninfoEndpointWithErrorResponse(options: MockOptions, httpStatus: number, responseBody?: object): void {
```
Comment (ISO50) [inline src/mock-tooling/index.ts]: @Retro64 @bzums 
Should we use number and or HttpStatus here?

Comment (Retro64) [reply src/mock-tooling/index.ts]: Would be fine for me as union type

File: src/mock-tooling/index.ts [hunk 2]
```diff
@@ -20,36 +20,68 @@ function generateToken(): Token {
...
-    // TODO: in the future we want to extrat scopes from body
+    // TODO: in the future we want to extract scopes from body
     const newToken = generateToken();
     tokens.push(newToken);
 
     return [HttpStatus.OK, newToken];
   });
 }
 
+export function mockAccessTokenEndpointWithErrorResponse(options: MockOptions, httpStatus: number, responseBody?: object): void {
```
Comment (ISO50) [inline src/mock-tooling/index.ts]: Since the mock does not set a content type we should probably return text instead object. Also the mock would be able to return plain strings.

File: test/unit/express-tooling.ts [hunk 3]
```diff
@@ -30,7 +30,7 @@ describe('express tooling', () => {
     next = sinon.spy();
 
     responseMock = {};
-    responseMock.sendStatus = sinon.spy((status: string) => {});
+    responseMock.sendStatus = sinon.spy((status: string) => { return {}; });
```
Comment (ISO50) [inline test/unit/express-tooling.ts]: or
`=> ({})`

File: test/unit/mock-tooling.ts [hunk 4]
```diff
@@ -19,4 +30,26 @@ describe('mock-tooling', () => {
       return expect(() => mockTooling.mockTokeninfoEndpoint({ url: ''} as MockOptions)).to.throw(Error);
     });
   });
+
+  describe('mockAccessTokenEndpointWithErrorResponse', () => {
+    it('should throw error, if url is empty', () => {
+      return expect(() => mockTooling.mockAccessTokenEndpointWithErrorResponse({ url: ''} as MockOptions, HttpStatus.BAD_REQUEST)).to.throw(Error);
+    });
+
+    it('should return status code, the mock is configured to use', () => {
```
Comment (ISO50) [inline test/unit/mock-tooling.ts]: `'should return specified/configured status code`

File: test/unit/mock-tooling.ts [hunk 5]
```diff
@@ -19,4 +30,26 @@ describe('mock-tooling', () => {
       return expect(() => mockTooling.mockTokeninfoEndpoint({ url: ''} as MockOptions)).to.throw(Error);
     });
   });
+
+  describe('mockAccessTokenEndpointWithErrorResponse', () => {
```
Comment (ISO50) [inline test/unit/mock-tooling.ts]: semanticially something like `mocked AccessTokenEndpointWithErrorResponse`makes more sense since we are not testing the returned value of 'mockAccessTokenEndpointWithErrorResponse' but the behavior of the installed mock.

File: CONTRIBUTING.md [hunk 6]
```diff
@@ -37,6 +37,7 @@ yourself, or create a new one that you would like work on and discuss your ideas
 ```
 
 - Make commits of logical units.
+- Lint your contribution by ```npm run tslint``` before committing
```
Comment (ISO50) [inline CONTRIBUTING.md]: Probably just a single \` intended?

File: test/unit/mock-tooling.ts (hunk 5 above)
Comment (Retro64) [reply test/unit/mock-tooling.ts]: ...called by the function mockAccessTokenEndpointWithErrorResponse - it is the test of the function

File: CONTRIBUTING.md (hunk 6 above)
Comment (ISO50) [inline CONTRIBUTING.md]: `before push` or `before commit`

File: test/unit/express-tooling.ts [hunk 7]
```diff
@@ -30,7 +30,7 @@ describe('express tooling', () => {
     next = sinon.spy();
 
     responseMock = {};
-    responseMock.sendStatus = sinon.spy((status: string) => {});
+    responseMock.sendStatus = sinon.spy((status: string) => ({}));
```
Comment (bzums) [inline test/unit/express-tooling.ts]: A suggestion for a discussion here @ISO50 @Retro64 I find it easier to follow the tests if all the "given state" is actually defined in the test case itself. I know that we often use `before` and `beforeEach` and I see the use case, but here I do not really see the need for it and it just seems to be cleaner if the declaration of `next` and `responseMock` would be in the test cases since that are actually the things we test. 

I am even wondering whether it would be better to also move the declaration of `requestMock` into the test cases. But there I do not see such a need cause we do no tests on this object, its purely for mocking and to keep things running as far as I see it. What do you think?

File: test/unit/mock-tooling.ts [hunk 8]
```diff
@@ -19,4 +30,26 @@ describe('mock-tooling', () => {
...
+    it('should throw error, if url is empty', () => {
+      return expect(() => mockTooling.mockAccessTokenEndpointWithErrorResponse({ url: ''} as MockOptions, HttpStatus.BAD_REQUEST)).to.throw(Error);
```
Comment (bzums) [inline test/unit/mock-tooling.ts]: `as MockOptions` should not be necessary. I guess its c&p from line 24 where for some reason a prop `auth: ''` is defined, I think that can be removed and then we do not need the `as` there anymore.

File: test/unit/mock-tooling.ts [hunk 9]
```diff
@@ -19,4 +30,26 @@ describe('mock-tooling', () => {
...
+      const expectedState = HttpStatus.BAD_REQUEST;
+      mockTooling.mockAccessTokenEndpointWithErrorResponse({ url } as MockOptions, expectedState);
+
+      const result = fetch(url, { method: 'POST' })
+        .then((data) => data.status);
+      return expect(result).to.become(expectedState);
+    });
+  });
+
+  describe('mockTokeninfoEndpointWithErrorResponse', () => {
```
Comment (bzums) [inline test/unit/mock-tooling.ts]: Maybe we could just test `mockEndpointWithErrorResponse` so we do not have to write each test multiple times?

File: test/unit/mock-tooling.ts [hunk 10]
```diff
@@ -19,4 +30,26 @@ describe('mock-tooling', () => {
       return expect(() => mockTooling.mockTokeninfoEndpoint({ url: ''} as MockOptions)).to.throw(Error);
     });
   });
+
+  describe('mockAccessTokenEndpointWithErrorResponse', () => {
+    it('should throw error, if url is empty', () => {
+      return expect(() => mockTooling.mockAccessTokenEndpointWithErrorResponse({ url: ''} as MockOptions, HttpStatus.BAD_REQUEST)).to.throw(Error);
+    });
+
+    it('should return specified/configured status code', () => {
```
Comment (bzums) [inline test/unit/mock-tooling.ts]: Add body object here as well, not only status code?

File: test/unit/express-tooling.ts (hunk 3 above)
Comment (bzums) [reply test/unit/express-tooling.ts]: or `=> undefined` ;)

File: test/unit/express-tooling.ts (hunk 7 above)
Comment (Retro64) [reply test/unit/express-tooling.ts]: Maybe as part of #132 as we decided to unify tests within this issue?

File: test/unit/mock-tooling.ts (hunk 9 above)
Comment (Retro64) [reply test/unit/mock-tooling.ts]: I am not sure if the test coverage would be lowered in this case...

File: src/mock-tooling/index.ts (hunk 1 above)
Comment (Retro64) [reply src/mock-tooling/index.ts]: we decided against, as the interface returns number or string

**Comment by bzums** [comment]
👍

**Comment by bzums** [comment]
👍

**Comment by Retro64** [comment]
:+1:

File: src/mock-tooling/index.ts (hunk 1 above)
Comment (ISO50) [reply src/mock-tooling/index.ts]: which interface are you speaking about?

Comment (ISO50) [reply src/mock-tooling/index.ts]: And what was with `responseBody: string`?

**Comment by ISO50** [comment]
👍
